In [1]:
import sunpy.map
import numpy as np
import os
import glob
import time


from scipy.ndimage.measurements import label, find_objects, center_of_mass
from scipy.ndimage.morphology import generate_binary_structure


#Root data dir
data_dir = os.path.abspath("/home/lazar/Fak(s)/AF/prakse/SDSA/data")

#Bitmap folder in data dir and search pattern for bitmaps
#idk if we need this, but whatever
bitmaps = sorted(glob.glob(os.path.join(
    data_dir, "3481_11923_SHARP_CEA_bitmaps/*bitmap*")))

#Intensity images folder and search pattern
cont_list = sorted(glob.glob(os.path.join(
    data_dir, "3481_11923_SHARP_CEA_enhanced_norm/*enhanced_normalized*")))

#Is this messy?
#Search pattern for Br, Bp, Bt in data_dir+magnetic_data_dir
magnetic_data_dir = os.path.join(
    data_dir, "3481_11923_SHARP_CEA_upscaled_magnetic_data")
Br_list = sorted(glob.glob(os.path.join(
    magnetic_data_dir, "*Br*")))
Bp_list = sorted(glob.glob(os.path.join(
    magnetic_data_dir, "*Bp*")))
Bt_list = sorted(glob.glob(os.path.join(
    magnetic_data_dir, "*Bt*")))

#Tree should look something like this
#
#/data_dir/
#├── 3481_11923_SHARP_CEA_bitmaps/SOME_NAME*_bitmap_*.fits
#├── 3481_11923_SHARP_CEA_enhanced_norm/SOME_NAME*__enhanced_normalized__*.fits
#└── 3481_11923_SHARP_CEA_upscaled_magnetic_data/SOME_NAME*__[Br, Bp, Bt]__*.fits
#

In [15]:
def get_patches_and_vectors(I, bx, by, bz, pixel_limit=20, thr=0.5, floodfill=4):
    '''
    I - intensity map for detecting pores; should be normalized to quiet sun
    bx - bx data (should be Bp from sharps) type should be sunpy map
    by - by data (should be Bt from sharps) type should be sunpy map. DO NOT CHANGE SIGN OF DATA, THIS FUNCTION WILL DO IT!
    bz - bz data (should be Br from sharps) type should be sunpy map
    pixel_limit - ignore patches that are smaller than this size
    thr - if I < thr => we assign it as pixel of interes; if data is normalized, 0.5 should work
    floodfill - in how many direction structure should perform flood fill
    https://en.wikipedia.org/wiki/Flood_fill
    
    floodfill = 4 looks in 4 direction and search structure looks like this
       [[0,1,0],
        [1,1,1],
        [0,1,0]]

    floodfill = 8 looks in 8 direction and search structure looks like this
        [[1,1,1],
         [1,1,1],
         [1,1,1]]
         
    Returns:
    
        This function returns two arrays:
        
        RETURN_MATRIX - Matrix that has data for patches center in dims [5xN] where N is number of patches.
        It is of folowing structure
        c_x[pix], c_y[pix], <Bx>[G], <By>[G], <Bz>[G]
        
        If there is no patches, this matrix is empty
        
        labeled_array - Matrix of same size as input intensity image
        if there are no patches this matrix is filled with zeros
         
    '''
    # Create masked array from I data
    if floodfill == 8:
        print("Using 8 directions search map %s" %(I.name))
        s = generate_binary_structure(2,2)
    else:
        print("Using 4 directions search map on %s" %(I.name))
        s = generate_binary_structure(2,1)
        
    
    X = np.ma.masked_where((I.data <= thr) & (I.data > 0), I.data)
    #LOL!
    #So, if mask is false (nothing satisfies condition), and you use structure in label
    #it will crash because its comparing structure off size [3,3] with 1D array
    #So lets handle it right here
    #And its faster at the end, we are leaving function right here
    if not X.mask.any():
        return np.zeros([]), np.zeros([I.data.shape[0],I.data.shape[1]])
    
    try:
        # sometimes this fails because of endianness
        # Select regions based on structures
        # labeled array is same dimension as input image
        labeled_array, num_features = label(X.mask, structure=s)
    except:
        labeled_array, num_features = label(X.mask.newbyteorder(), structure=s)

  
    # find how many pixel is in each patch
    regions, counts = np.unique(labeled_array, return_counts=True)
            
    # if pixel count for patch is smaller then pixel_limit
    # This labels of patches with small pixel count
    remove_patches = (counts < pixel_limit).nonzero()[0]
    # Set it to zero
    for i in remove_patches:
        labeled_array[labeled_array == i] = 0

    # THIS IS LAZY PROGRAMMING!!! DONT DO THIS!
    # i wanted smooth region labelin (0,1,2,3,4) not gapped (0,1,4,6,7), i could do that manually, but im lazy
    # I cant overwrite labeled_array variable because im using it later in cmass
    labeled_array1, num_features1 = label(labeled_array)

    #Check again if we removed all features because of trh for region of interest
    #I tought that we are smarter than nested if/elif/else
    if num_features1 == 0:
        return np.zeros([]), np.zeros([I.data.shape[0],I.data.shape[1]])
      
    #######
    # lets calculate centers of patches
    # Actuall patches are marked as 1 and above, 0 is background
    elif num_features1 == 1:
        features_label = np.array([1])
    else:
        #it has to be +1 because arange (1,2,1) returns [1], same as above!!!
        features_label = np.arange(1, num_features1+1, 1)
    cmass = center_of_mass(labeled_array, labeled_array1, features_label)
    # print(labeled_array)

    # Create placeholder matrix that has
    # cx[pix], cy[pix], <bx>[G], <by>[G], <bz>[G]
    # 
    #because 0 is not feature we are interested in
    #print(num_features1)
    RETURN_MATRIX = np.zeros([num_features1, 5])

    for pore_index in features_label:
        # valid pixels for that pore index over which we should average
        valid_pixels = np.argwhere(labeled_array1 == pore_index)
        # for some reason x is normal here
        RETURN_MATRIX[pore_index - 1][0] = cmass[pore_index-1][0]
        RETURN_MATRIX[pore_index - 1][1] = cmass[pore_index-1][1]
        RETURN_MATRIX[pore_index - 1][2] = np.mean(bx.data[valid_pixels[:, 0], valid_pixels[:, 1]])
        #Note that here we are using -by because Bt = -By
        RETURN_MATRIX[pore_index - 1][3] = np.mean(-by.data[valid_pixels[:, 0], valid_pixels[:, 1]])
        RETURN_MATRIX[pore_index - 1][4] = np.mean(bz.data[valid_pixels[:, 0], valid_pixels[:, 1]])

    return RETURN_MATRIX, labeled_array1

    #, labeled_array1

def touch(path):
    '''
    Create empty file
    '''
    with open(path, 'a'):
        os.utime(path, None)

In [17]:

#lets make it work first

from multiprocessing import Pool
nproc = 4  # i have 4 cores + hyperthreading (dont want to set my pc on fire)

out_dir_for_patches = os.path.join(data_dir,'patches_dir_test')
#UGLY!!!!!
replace_this = 'enhanced_normalized.fits'
with_this = 'patches.txt'
def parallel_wrap(i):
    I = sunpy.map.Map(cont_list[i])
    #print(I.data.shape)
    bz = sunpy.map.Map(Br_list[i])
    #print(bz.data.shape)
    bx = sunpy.map.Map(Bp_list[i])
    #print(bx.data.shape)
    by = sunpy.map.Map(Bt_list[i])
    #print(by.data.shape)
    save_matrix, _ = get_patches_and_vectors(I, bx, by, bz)
    print(save_matrix)
    #outfile = os.path.basename(cont_list[i]).replace(
    #    replace_this, with_this)
    #ofile = os.path.join(out_dir_for_patches, outfile)
    #if save_matrix.size == 1:# == None:
    #    touch(ofile)
    #    return
    #    continue
    #np.savetxt(ofile, save_matrix)
    return


for i in range(200,250):
    parallel_wrap(i)
#if __name__ == '__main__':
#    p = Pool(nproc)
#    start = time.time()
#    p.map(parallel_wrap, np.arange(len(cont_list)))
#    end = time.time()
#    print(end - start)

Using 4 directions search map on HMI hmi 2013-12-10 03:10:10
1
[0 1]
[[  593.79775281  1253.37078652    -2.13550842    78.28698579
  -1461.02583348]]
Using 4 directions search map on HMI hmi 2013-12-10 03:22:10
1
[0 1]
[[  593.39361702  1253.57446809    -6.52614749    92.83597577
  -1456.5230167 ]]
Using 4 directions search map on HMI hmi 2013-12-10 03:34:10
2
[0 1 2]
[[  593.25882353  1252.95294118    21.33278079   104.49062015
  -1481.45559072]
 [  617.36363636  1268.59090909  -166.54775932  -498.88201465
  -1253.12527604]]
Using 4 directions search map on HMI hmi 2013-12-10 03:46:10
1
[0 1]
[[  593.76190476  1253.51190476    28.19306331    60.99130245
  -1502.82927381]]
Using 4 directions search map on HMI hmi 2013-12-10 03:58:10
2
[0 1 2]
[[  593.1011236   1254.01123596    46.30975261    87.64362335
  -1487.79401661]
 [  610.5         1030.          -155.43188049   245.57512685
   1345.00850866]]
Using 4 directions search map on HMI hmi 2013-12-10 04:10:10
2
[0 1 2]
[[  593.2911392

[[ 655.80530973 1127.6460177  -139.2082919   116.94849157 1332.61242861]]


HMI hmi 2013-12-08 13:10:10
